apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: service-b
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor-c
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: service-c
  endpoints:
    - port: http
      path: /metrics
      interval: 10s